# Generated by Django 5.1.3 on 2024-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(default='title', max_length=10),
            preserve_default=False,
        ),
    ]
