# Generated by Django 5.1.3 on 2024-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('con_password', models.TextField()),
            ],
        ),
    ]
